name: "Upgrade Python3 package"
description: "Upgrading Python3 package on different operating systems"
iputis:
  python3-version:
    description: "Python3 version which should be installed"
    default: "13"
    required: true
  operating-system:
    description: "Base operating system which Python3 package should be upgraded. Available options: ubuntu-24.04/windows-2022/macos-14"
    default: "ubuntu-24.04"
    required: true

runs:
  using: "composite"
  steps:
    - name: upgrade-python3-pacakge-on-linux
      if: contains(inputs.operating-system, 'ubuntu-24.04')
      shell: bash
      run: |
        sudo apt update && \
        sudo apt install build-essential software-properties-common -y && sudo add-apt-repository ppa:deadsnakes/ppa && \
        sudo apt update && \
        sudo apt install python3.${{ inputs.python3-version }} python3.${{ inputs.python3-version }}-venv -y
        python --version

    - name: upgrade-python3-pacakge-on-windows
      if: contains(inputs.operating-system, 'windows-2022')
      shell: bash
      run: |
        choco install --force python3${{ inputs.python3-version }} --pre
        python --version

    - name: upgrade-python3-package-on-ios
      if: contains(inputs.operating-system, 'macos-14')
      shell: bash
      run: |
        brew install python@3.${{ inputs.python3-version }}
        python --version
