name: "Upgrade CMake on Linux"
description: "Upgrade CMake on Linux before compiling C++ project"

inputs:
  cmake-version:
    description: "CMake version which should be installed"
    default: "3.30.3"
    required: true
  target-os:
    description: "Operating system which will be used to upgrade CMake package. Options: ubuntu-24.04/windows-2022/macos-14"
    default: 'ununtu-24.04'
    required: true

runs:
  using: "composite"
  steps:
  - name: upgrade-cmake-on-ubuntu
    if: contains(inputs.target-os, 'ubuntu-24.04')
    shell: bash
    run: |
      wget https://github.com/Kitware/CMake/releases/download/v${{ inputs.cmake-version }}/cmake-${{ inputs.cmake-version }}-linux-x86_64.tar.gz
      tar -xzf cmake-${{ inputs.cmake-version }}-linux-x86_64.tar.gz
      sudo mv cmake-${{ inputs.cmake-version }}-linux-x86_64 /opt/cmake-${{ inputs.cmake-version }}
      sudo ln -sf /opt/cmake-${{ inputs.cmake-version }}/bin/* /usr/local/bin/
      cmake --version
  - name: upgrade-cmake-on-windows
    if: contains(inputs.target-os, 'windows-2022')
    shell: bash
    run: |
      choco install cmake --version=${{ inputs.cmake-version }} --allow-downgrade
      cmake --version
  - name: upgrade-cmake-version-on-ios
    if: contains(inputs.target-os, 'macos-14')
    shell: bash
    run: |
      curl -LO https://github.com/Kitware/CMake/releases/download/v${{ inputs.cmake-version }}/cmake-${{ inputs.cmake-version }}-macos-universal.tar.gz
      tar -xzf cmake-${{ inputs.cmake-version }}-macos-universal.tar.gz
      sudo cp -R cmake-${{ inputs.cmake-version }}-macos-universal/CMake.app /Applications/
      sudo ln -sf /Applications/CMake.app/Contents/bin/* /usr/local/bin/
      cmake --version
